### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by xuchunyu123** [Vidhiwar/multimodal-ecg-classification#1]
Hi  Vidhiwar :
Thank you for reading!
I am a second-year  graduate student  at ECUST University, China. 
My research is focused on Signal Classification. I have recently read your paper: " Multi-module Recurrent Convolutional Neural Network with Transformer Encoder for ECG Arrhythmia Classification".
I am wondering if you could kindly send me the  dataset and the necessary information about it，especially ECG_Data_Collect.xlsx. I promise they will be used only for research purposed.
Thank you very much for your kind consideration and I am looking forward to your early reply.

All the best,

Emial:
y80200033@mail.ecust.edu.cn

**Comment by Vidhiwar** [comment]
Hello, The ECG_Data_Collect.xlsx file can be accessed through this link.
https://docs.google.com/spreadsheets/d/1kz_V_SsQyaSj7VG-LrICeOTjNO_CsiLq/edit?usp=sharing&ouid=106405350764582233648&rtpof=true&sd=true
