### ISSUE TITLE
ECG_Data_Collect.xlsx

### ISSUE THREAD

**Issue by LLLL1021** [Vidhiwar/multimodal-ecg-classification#2]
Hello, I want to run this code, but this file(ECG_Data_Collect.xlsx) is missing. Could you please upload it? Or send it to my e-mail, my e-mail is 1799892247@qq.com, or could you please tell me what data and format are in this xlsx file? Thank you for your trouble! Gods bless kind people

**Comment by Vidhiwar** [comment]
Hello, The ECG_Data_Collect.xlsx file can be accessed through this link. 
https://docs.google.com/spreadsheets/d/1kz_V_SsQyaSj7VG-LrICeOTjNO_CsiLq/edit?usp=sharing&ouid=106405350764582233648&rtpof=true&sd=true
