### ISSUE TITLE
STFT

### ISSUE THREAD

**Issue by LLLL1021** [Vidhiwar/multimodal-ecg-classification#3]
Hello, I would like to ask, when I use your code for this step of STFT transform with MiT-BiH dataset, why the generated spectrograms are all the same? Do you know what is wrong? Thank you very much！

**Comment by Vidhiwar** [comment]
Hi, Thanks for reaching out. I am not sure I understand your problem. In my experiments the STFT transforms for various windows looked similar but was different. Could you share some samples that look similar?
