### ISSUE TITLE
ecg_phy2017.py in each epoch have the same result

### ISSUE THREAD

**Issue by Zzzoptimus** [Vidhiwar/multimodal-ecg-classification#5]
Hello,thanks for your  excellent work.I've already finished the dataset(STFT transform with phy2017).
Then i use "python ecg_phy2017.py"in my terminal.I set the batchsize to 10(because I have only 20GB gpu memory,otherwise will out of memory).
But the results of every epoch always the same. Do you know what is wrong?

**Comment by Vidhiwar** [comment]
Hello, I added the phy2017 dataset just as a benchmark. However, the training and testing for this project was done on MITBIH
